version: "3.8"
#Para servidor Linux
services:
  php8-fpm:
    image: urnau/php-fiap-hmv-backend
    build: .
    networks:
      - net_db_exemplo
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
networks:
  net_db_exemplo: